In [1]:
import pandas as pd
import matplotlib.pyplot as plt
spreadsheet = pd.ExcelFile('Dataset/dataset.xlsx')
df2 = spreadsheet.parse('Sheet1')
df2.head()

State_Name District_Name  Crop_Year       Season       Crop  Area(ha)  \
0  Maharashtra    AHMEDNAGAR     1997.0  Kharif       Arhar/Tur   17600.0   
1  Maharashtra    AHMEDNAGAR     1997.0  Kharif           Bajra  274100.0   
2  Maharashtra    AHMEDNAGAR     1997.0  Kharif            Gram   40800.0   
3  Maharashtra    AHMEDNAGAR     1997.0  Kharif           Jowar     900.0   
4  Maharashtra    AHMEDNAGAR     1997.0  Kharif           Maize    4400.0   

   Production(tonnes)  Avg_Prep(mm)  Avg_temp(C)  Yield(tonnes/ha)  
0              6300.0     136.30175        25.65          0.357955  
1            152800.0     136.30175        25.65          0.557461  
2             18600.0     136.30175        25.65          0.455882  
3              1100.0     136.30175        25.65          1.222222  
4              4700.0     136.30175        25.65          1.068182

In [2]:
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D

ar = []
ar2d = []

x_list=[]
z_list=[]
i=0
y_list=[]
for row in df2.itertuples():
    if row[5]=='Bajra':
        ar.append(row[8])
        x_list.append(row[8])
        ar.append(row[9])
        z_list.append(row[9])
        y_list.append(row[10])
        ar2d.append(ar)
        ar = []
    i=i+1
nar2d = np.array(ar2d)
ny = np.array(y_list)


X_train = nar2d[:-3]
X_test = nar2d[-3:]

y_train = ny[:-3]
y_test = ny[-3:]

'''
print(X_train)
print(X_test)
print(y_train)
'''
print(y_test)


# Fit line using all data
lr = linear_model.LinearRegression()
lr.fit(X_train, y_train)
line_y = lr.predict(X_test)
print("Linear regression prediction")
print(line_y)

# Robustly fit linear model with RANSAC algorithm
ransac = linear_model.RANSACRegressor()
ransac.fit(X_train, y_train)
inlier_mask = ransac.inlier_mask_
outlier_mask = np.logical_not(inlier_mask)

line_y_ransac = ransac.predict(X_test)
print("ransac prediction")
print(line_y_ransac)
# Compare estimated coefficients
print("Estimated coefficients (linear regression, RANSAC):")
print(lr.coef_, ransac.estimator_.coef_)

# The mean squared error
print("Mean squared error of linear regression: %.2f"
      % mean_squared_error(y_test, line_y))
print("Mean squared error of ramsac regression: %.2f"
      % mean_squared_error(y_test, line_y_ransac))
# Explained variance score: 1 is perfect prediction
print('Variance score of linear regr: %.2f' % r2_score(y_test, line_y))
print('Variance score of ransac: %.2f' % r2_score(y_test, line_y_ransac))

[0.63043478 0.36486486 0.625     ]
Linear regression prediction
[0.65001046 0.61809109 0.63771798]
ransac prediction
[0.52117874 0.47647599 0.49840548]
Estimated coefficients (linear regression, RANSAC):
[0.00071077 0.00401044] [0.00097385 0.01543357]
Mean squared error of linear regression: 0.02
Mean squared error of ramsac regression: 0.01
Variance score of linear regr: -0.40
Variance score of ransac: 0.12


In [3]:
ar = []
ar2d = []

x_list=[]
z_list=[]
i=0
y_list=[]
for row in df2.itertuples():
    if row[5]=='Jowar':
        ar.append(row[8])
        x_list.append(row[8])
        ar.append(row[9])
        z_list.append(row[9])
        y_list.append(row[10])
        ar2d.append(ar)
        ar = []
    i=i+1
nar2d = np.array(ar2d)
ny = np.array(y_list)


X_train = nar2d[:-3]
X_test = nar2d[-3:]

y_train = ny[:-3]
y_test = ny[-3:]

'''
print(X_train)
print(X_test)
print(y_train)
'''
print(y_test)


# Fit line using all data
lr = linear_model.LinearRegression()
lr.fit(X_train, y_train)
line_y = lr.predict(X_test)
print("Linear regression prediction")
print(line_y)

# Robustly fit linear model with RANSAC algorithm
ransac = linear_model.RANSACRegressor()
ransac.fit(X_train, y_train)
inlier_mask = ransac.inlier_mask_
outlier_mask = np.logical_not(inlier_mask)

line_y_ransac = ransac.predict(X_test)
print("ransac prediction")
print(line_y_ransac)
# Compare estimated coefficients
print("Estimated coefficients (linear regression, RANSAC):")
print(lr.coef_, ransac.estimator_.coef_)

# The mean squared error
print("Mean squared error of linear regression: %.2f"
      % mean_squared_error(y_test, line_y))
print("Mean squared error of ramsac regression: %.2f"
      % mean_squared_error(y_test, line_y_ransac))
# Explained variance score: 1 is perfect prediction
print('Variance score of linear regr: %.2f' % r2_score(y_test, line_y))
print('Variance score of ransac: %.2f' % r2_score(y_test, line_y_ransac))

[1.         1.18077475 1.        ]
Linear regression prediction
[0.58208825 1.15194569 0.57393827]
ransac prediction
[0.65423131 0.98102254 0.72584911]
Estimated coefficients (linear regression, RANSAC):
[ 0.00553711 -0.09166601] [1.49725283e-05 1.82041785e-01]
Mean squared error of linear regression: 0.12
Mean squared error of ramsac regression: 0.08
Variance score of linear regr: -15.39
Variance score of ransac: -9.77


In [4]:
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D

ar = []
ar2d = []

x_list=[]
z_list=[]
i=0
y_list=[]
for row in df2.itertuples():
    if row[5]=='Urad':
        ar.append(row[8])
        x_list.append(row[8])
        ar.append(row[9])
        z_list.append(row[9])
        y_list.append(row[10])
        ar2d.append(ar)
        ar = []
    i=i+1
nar2d = np.array(ar2d)
ny = np.array(y_list)


X_train = nar2d[:-3]
X_test = nar2d[-3:]

y_train = ny[:-3]
y_test = ny[-3:]

'''
print(X_train)
print(X_test)
print(y_train)
'''
print(y_test)


# Fit line using all data
lr = linear_model.LinearRegression()
lr.fit(X_train, y_train)
line_y = lr.predict(X_test)
print("Linear regression prediction")
print(line_y)

# Robustly fit linear model with RANSAC algorithm
ransac = linear_model.RANSACRegressor()
ransac.fit(X_train, y_train)
inlier_mask = ransac.inlier_mask_
outlier_mask = np.logical_not(inlier_mask)

line_y_ransac = ransac.predict(X_test)
print("ransac prediction")
print(line_y_ransac)
# Compare estimated coefficients
print("Estimated coefficients (linear regression, RANSAC):")
print(lr.coef_, ransac.estimator_.coef_)

# The mean squared error
print("Mean squared error of linear regression: %.2f"
      % mean_squared_error(y_test, line_y))
print("Mean squared error of ramsac regression: %.2f"
      % mean_squared_error(y_test, line_y_ransac))
# Explained variance score: 1 is perfect prediction
print('Variance score of linear regr: %.2f' % r2_score(y_test, line_y))
print('Variance score of ransac: %.2f' % r2_score(y_test, line_y_ransac))

[0.49802372 0.324      0.40530303]
Linear regression prediction
[0.50695218 0.49055447 0.51975522]
ransac prediction
[0.48101094 0.46107515 0.49426228]
Estimated coefficients (linear regression, RANSAC):
[ 0.00043936 -0.0317089 ] [ 0.00052518 -0.03446297]
Mean squared error of linear regression: 0.01
Mean squared error of ramsac regression: 0.01
Variance score of linear regr: -1.70
Variance score of ransac: -0.78
